name: smart_agent
description: A local offline order app built with Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Local database
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.2

  # State management
  provider: ^6.1.1

  # App storage
  shared_preferences: ^2.2.2

  # PDF export
  pdf: ^3.10.4
  printing: ^5.12.0

  # One-time activation (HTTP)
  http: ^1.2.0
  device_info_plus: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

